// <auto-generated />
using System;
using IrrigationServer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IrrigationServer.Migrations
{
    [DbContext(typeof(IrrigationDbContext))]
    partial class IrrigationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IrrigationServer.Models.Meres", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("MertAdat")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Mikor")
                        .HasColumnType("datetime2");

                    b.Property<long>("SzenzorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SzenzorId");

                    b.ToTable("Meresek");
                });

            modelBuilder.Entity("IrrigationServer.Models.Szenzor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Megjegyzes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipus")
                        .HasColumnType("int");

                    b.Property<long>("ZonaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("Szenzorok");
                });

            modelBuilder.Entity("IrrigationServer.Models.Zona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zonak");
                });

            modelBuilder.Entity("IrrigationServer.Models.Meres", b =>
                {
                    b.HasOne("IrrigationServer.Models.Szenzor", "Szenzor")
                        .WithMany("Meresek")
                        .HasForeignKey("SzenzorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IrrigationServer.Models.Szenzor", b =>
                {
                    b.HasOne("IrrigationServer.Models.Zona", "Zona")
                        .WithMany("Szenzorok")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
